-- phpMyAdmin SQL Dump
-- version 4.0.10.15
-- http://www.phpmyadmin.net
--
-- Хост: 127.0.0.1
-- Время создания: Мар 05 2017 г., 13:32
-- Версия сервера: 5.1.69-community-log
-- Версия PHP: 5.3.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- База данных: `A880513_WorkSafe`
--

-- --------------------------------------------------------

--
-- Структура таблицы `commentsetings`
--

CREATE TABLE IF NOT EXISTS `commentsetings` (
  `id` int(1) NOT NULL AUTO_INCREMENT,
  `url_type` int(1) NOT NULL,
  `rules` text NOT NULL,
  `comment_max` int(3) NOT NULL,
  `send` int(1) NOT NULL,
  `mail` varchar(60) NOT NULL,
  `pass` varchar(15) NOT NULL,
  `theme` varchar(60) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Структура таблицы `commentsystem`
--

CREATE TABLE IF NOT EXISTS `commentsystem` (
  `id` int(4) NOT NULL AUTO_INCREMENT,
  `parent_id` int(4) NOT NULL,
  `url_id` varchar(300) NOT NULL,
  `id_material` varchar(11) NOT NULL,
  `name` varchar(30) NOT NULL,
  `profession` varchar(20) NOT NULL,
  `url` varchar(30) NOT NULL,
  `mail` varchar(60) NOT NULL,
  `text` varchar(500) NOT NULL,
  `date_add` varchar(18) NOT NULL,
  `public` int(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=135 ;

--
-- Дамп данных таблицы `commentsystem`
--

INSERT INTO `commentsystem` (`id`, `parent_id`, `url_id`, `id_material`, `name`, `profession`, `url`, `mail`, `text`, `date_add`, `public`) VALUES
(7, 0, 'alltop-und-billig.de/bewertungen.php', '', 'Stiven', 'Automechaniker', 'as1252', 'mail@example.com', 'Danke! Handschuhe waren schon am nächsten Tag da die Qualität scheint gut zu sein. Ich weiß nicht, ob sie besser oder schlechter als Mafiflex sind, aber mit der zeit wird es sich herausstellen. In der Zeitung pdf habe ich einen schwedischen test gesehen wenn sie mir gefallen, werde ich weitere bestellen.', '17.03.2014', 1),
(10, 0, 'alltop-und-billig.de/bewertungen.php', '', 'Bob', 'Trockenbauer', 'edf258', 'mail@example.com', 'Ein interessantes system mit der Bestellnummer für Kommentare. Nun sind sie da sitzen gut unterscheiden sich nicht von dem anderen Modell, besonders der preis freut mich.', '11.04.2014', 1),
(11, 0, 'alltop-und-billig.de/bewertungen.php', '', 'Christian', 'Polier', 'ed?258', 'mail@example.com', 'Hallo! Es sieht so aus, dass ich unter die drei ersten Käufer komme! Ich möchte sagen, dass die internetseite sehr interessant ist, alles verständlich gelesen und gleich bestellt. Zuerst hate ich Zweifel ob die Bestellung ankomt, aber drei Tage später war alles da. Danke nochmal!!!', '18.04.2014', 1),
(13, 0, 'alltop-und-billig.de/bewertungen.php', '', 'Bastian', 'Bauhelfer', 'ekn656', 'mail@example.com', 'Ich kenne mich mit der Qualität nicht aus, für mich ist alles das gleiche. Was mich zum Kauf gebracht hat ist Ihr Preis :) Wenn sie beim zweiten mal nicht kaputt gehen, dann werde ich Sie an alle meine bekannten Bauarbeiter weiterempfehlen.', '13.05.2014', 1),
(14, 0, 'alltop-und-billig.de/bewertungen.php', '', 'Burck', 'Rolleger', 'as1234', 'mail@mail.com', 'Sehr gute Handschuhe, habe ähnliche auf schwedischen Internetseiten gefunden. Bei Ihnen ist der Preis deutlich niedriger, schade dass man nich immer 30 Euro über hat, um ein weiteres paar zu kaufen, obwohl handschuhe sind immer nützlich. Schöne Seite!', '20.05.2014', 1),
(15, 0, 'alltop-und-billig.de/bewertungen.php', '', 'Timur', 'Metallbau', 'as1234', 'mail@mail.com', 'Ich arbeite mit metallischen Werkstücken, bei mir gehen alle Handschuhe schnell kaputt. Der Preis warsehr attraktiv, wenn ich ehrlich bin, der verkaufspreis bei ebay ist 2 mal höher, und solche Handschuhe gibt es nur bei euch.', '27.05.2014', 1),
(17, 0, 'alltop-und-billig.de/bewertungen.php', '', 'Michael', 'Fliesenleger', 'as1234', 'mail@mail.com', 'Hallo! Ein Kollege hat mir die internetseite empfohlen. Die Handschuhe waren schon am nächsten tag da! Schnell! danke! Werde sie gleich ausprobieren...', '03.06.2014', 1),
(18, 0, 'alltop-und-billig.de/bewertungen.php', '', 'Jens', 'Elektriker', 'as1128', 'mail@mail.com', 'Gute Ware zu einem attraktiven Preis ist eine seltenheit. Warum habe ich wie in einer anderen Farbe als auf dem Bild? Werden die Größen farbllich unterschiden? Interessante idee.', '10.06.2014', 1),
(19, 0, 'alltop-und-billig.de/bewertungen.php', '', 'Kris', 'Trockenbauer', 'fr1599', 'mail@mail.com', 'Ich habe diese Handschuhe gekauft, weil ein Bekannter von mir ähnliche hat. Sind super verarbeitet, gute Qualität, toller Tragekomfort und sie schmiegen sich gut an der Hand plus schnelle Lieferung und bequeme Bezahlung.', '10.07.2014', 1),
(60, 0, 'alltop-und-billig.de/bewertungen.php', '', 'Andreas', 'Maler', 'as5855', '', 'Diese Handschuhe sind gut zu tragen, sicheres gefühl bei der arbeit kann ich nur weiterempfehlen. Habe lange damit gearbeitet uns sie sind immer noch im guten Zustand. Immer wieder gerne.', '19.07.2014', 1);

-- --------------------------------------------------------

--
-- Структура таблицы `log`
--

CREATE TABLE IF NOT EXISTS `log` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `log` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=36 ;

--
-- Дамп данных таблицы `log`
--

INSERT INTO `log` (`id`, `log`) VALUES
(1, '{"mc_gross":"0.01","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"11:08:31 Jul 12, 2014 PDT","payment_status":"Completed","charset":"windows-1252","address_zip":"10367","first_name":"Sergejs","mc_fee":"0.01","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"AHoXI6Hmn.TctDB23KkC8vphheQ3Ao34pIzp424QL.wMllBBSUQczwhn","payer_email":"vasja.forum@gmail.com","txn_id":"43789964MP6413434","payment_type":"instant","btn_id":"83675706","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 10","discount":"0.00","mc_currency":"EUR","item_number":"001","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"d16d7dab106f8"}'),
(2, '{"mc_gross":"0.01","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"11:16:41 Jul 12, 2014 PDT","payment_status":"Completed","charset":"windows-1252","address_zip":"10367","first_name":"Sergejs","mc_fee":"0.01","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"AK3xJLZtUN1pP1CmulMf1V0ugf9HAjm5EhxOUe6qK0mGcy69eswOEcn7","payer_email":"vasja.forum@gmail.com","txn_id":"85248002T7600411A","payment_type":"instant","btn_id":"83675706","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 10","discount":"0.00","mc_currency":"EUR","item_number":"001","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"523b47af91260"}'),
(3, ''),
(4, 'INSERT INTO `payments` (name, address, email, item_name, count, trid, status) VALUES (''buyer Lavrovs'', ''Germany Freiburg st. ESpachstr. 1 zip: 79111'', ''buyer@testme.com'', ''WorkSafe Pre Grobe 10'', ''1'', ''5D666164X52603804, ''Completed'')'),
(5, 'INSERT INTO `payments` (name, address, email, item_name, count, trid, status) VALUES (''buyer Lavrovs'', ''Germany Freiburg st. ESpachstr. 1 zip: 79111'', ''buyer@testme.com'', ''WorkSafe Pre Grobe 10'', ''1'', ''3VL687105W469483U, ''Completed'')'),
(6, 'INSERT INTO `payments` (name, address, email, item_name, count, trid, status) VALUES (''buyer Lavrovs'', ''Germany Freiburg st. ESpachstr. 1 zip: 79111'', ''buyer@testme.com'', ''WorkSafe Pre Grobe 10'', ''1'', ''57373151683265907'', ''Completed'')'),
(7, '{"mc_gross":"0.01","protection_eligibility":"Eligible","address_status":"unconfirmed","payer_id":"ET2GVW7CCBCEU","tax":"0.00","address_street":"ESpachstr. 1","payment_date":"11:58:55 Jul 12, 2014 PDT","payment_status":"Completed","charset":"windows-1252","address_zip":"79111","first_name":"buyer","mc_fee":"0.01","address_country_code":"DE","address_name":"buyer Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"seller@testme.com","address_country":"Germany","address_city":"Freiburg","quantity":"1","verify_sign":"Ai1PaghZh5FmBLCDCTQpwG8jB264A96aHdaAW.c40IepU7lYwOPRx7LM","payer_email":"buyer@testme.com","txn_id":"8B729345X1509483S","payment_type":"instant","btn_id":"2972702","last_name":"Lavrovs","address_state":"Empty","receiver_email":"seller@testme.com","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"E8HYNGMBCNFQN","txn_type":"web_accept","item_name":"WorkSafe Pre Grobe 10","discount":"0.00","mc_currency":"EUR","item_number":"10","residence_country":"DE","test_ipn":"1","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"fb819bb47e355"}'),
(8, '{"mc_gross":"0.01","protection_eligibility":"Eligible","address_status":"unconfirmed","payer_id":"ET2GVW7CCBCEU","tax":"0.00","address_street":"ESpachstr. 1","payment_date":"12:00:27 Jul 12, 2014 PDT","payment_status":"Completed","charset":"windows-1252","address_zip":"79111","first_name":"buyer","mc_fee":"0.01","address_country_code":"DE","address_name":"buyer Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"seller@testme.com","address_country":"Germany","address_city":"Freiburg","quantity":"1","verify_sign":"Aw3HlEKnD7aBeN-U1jVUV2Mau8qeAwCiu2RWGCukrkt1TywLw8JqQoWB","payer_email":"buyer@testme.com","txn_id":"60162371EK407782F","payment_type":"instant","btn_id":"2972702","last_name":"Lavrovs","address_state":"Empty","receiver_email":"seller@testme.com","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"E8HYNGMBCNFQN","txn_type":"web_accept","item_name":"WorkSafe Pre Grobe 10","discount":"0.00","mc_currency":"EUR","item_number":"10","residence_country":"DE","test_ipn":"1","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"2f68845bba37a"}'),
(9, 'INSERT INTO `payments` (name, address, zip, email, item_name, trid, status, archive) VALUES (''Sergejs Lavrovs'', ''Weissenseer Weg 13\\r\\nbei Kharitonova'', ''10367'', ''vasja.forum@gmail.com'', ''WorkSafe Precision 10'', ''23W5871787814962P'', ''Completed'', 0)'),
(10, 'INSERT INTO `payments` (name, address, zip, email, item_name, trid, status, archive) VALUES ('' '', '''', '''', '''', '''', '''', '''', 0)'),
(11, 'INSERT INTO `payments` (name, address, zip, email, item_name, trid, status, archive) VALUES (''asdasdasd'', ''asdasdasdasd'', ''sdfgdfgdfg'', ''asdfdsgedf'', ''sdfgergdsg'', ''rdegtrehyrt'', ''dfhgdfdfgbedfgf'', 0)'),
(12, 'INSERT INTO `payments` (name, address, zip, email, item_name, trid, status, archive) VALUES (''Sergejs Lavrovs'', ''Weissenseer Weg 13\\r\\nbei Kharitonova'', ''10367'', ''vasja.forum@gmail.com'', ''WorkSafe Precision 10'', ''9K958255GF1404438'', ''Completed'', 0)'),
(13, '{"mc_gross":"0.01","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\nbei Kharitonova","payment_date":"14:17:31 Jul 18, 2014 PDT","payment_status":"Completed","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","mc_fee":"0.01","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"Axq8wpcV1L0MgD22-jTkyYQ6h7AOAqOZDwDQn.Y7vY.KEnhGgm4UxoPk","payer_email":"vasja.forum@gmail.com","contact_phone":"017661995963","txn_id":"51D377857H488332P","payment_type":"instant","btn_id":"83675706","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 10","discount":"0.00","mc_currency":"EUR","item_number":"001","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"9d3ac0ef5e67"}'),
(14, '{"mc_gross":"0.01","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\r\nbei Kharitonova","payment_date":"14:25:35 Jul 18, 2014 PDT","payment_status":"Completed","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","mc_fee":"0.01","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"ApjIuwdrSy-vAy7niMbDBaoHGxT5A7mulJLpgw8EftkXDwTp.bQHaMmx","payer_email":"vasja.forum@gmail.com","contact_phone":"017661995963","txn_id":"1GU46678792452538","payment_type":"instant","btn_id":"83675706","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 10","discount":"0.00","mc_currency":"EUR","item_number":"001","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"ddfe5c9ead483"}'),
(15, '{"mc_gross":"0.01","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\nbei Kharitonova","payment_date":"14:43:48 Jul 18, 2014 PDT","payment_status":"Completed","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","mc_fee":"0.01","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"A9q33sUt.ixnFNZ.aBeeN0xayU2hAKybBErZ2UOu3EHTiudFnxpFTDyy","payer_email":"vasja.forum@gmail.com","contact_phone":"017661995963","txn_id":"5A3854717V5297543","payment_type":"instant","btn_id":"83675706","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 10","discount":"0.00","mc_currency":"EUR","item_number":"001","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"219b2959d1c99"}'),
(18, '{"mc_gross":"0.01","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"13:19:10 Jul 20, 2014 PDT","payment_status":"Completed","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","mc_fee":"0.01","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"AlAlnsACWRTf4OV6vRMZG4sCyEdYARftuc7LTm3y6NA5xllv3at2or6m","payer_email":"vasja.forum@gmail.com","contact_phone":"017661995963","txn_id":"0AG52895N95361104","payment_type":"instant","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"fe50a208a8298"}'),
(19, '{"mc_gross":"0.01","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"13:20:19 Jul 20, 2014 PDT","payment_status":"Completed","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","mc_fee":"0.01","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"AOE0O5TphUb8mZvEVC-DZY3wKgKtATHfh-nV3ffms4khY-4MJeRhGNHM","payer_email":"vasja.forum@gmail.com","contact_phone":"017661995963","txn_id":"33P67818SY036720P","payment_type":"instant","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"96b9738811b9e"}'),
(20, '{"mc_gross":"0.01","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"10:11:35 Jul 21, 2014 PDT","payment_status":"Completed","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","mc_fee":"0.01","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"AS-3SKSqiWYUSXAUHOtgpgbir-qeASyexhtG.A7Rb7-U30eecR7eIMbD","payer_email":"vasja.forum@gmail.com","contact_phone":"017661995963","txn_id":"22011613RR162264D","payment_type":"instant","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"f0762706e0925"}'),
(21, '{"mc_gross":"0.01","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"10:12:48 Jul 21, 2014 PDT","payment_status":"Completed","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","mc_fee":"0.01","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"Ag5H92pdBuyGHrpX9TUyC83rCa.tAR9.ZxbgUab8DmoYmw53vFqF2XEQ","payer_email":"vasja.forum@gmail.com","contact_phone":"017661995963","txn_id":"00B09396A21740843","payment_type":"instant","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"8d892f709d6ac"}'),
(22, '{"mc_gross":"-0.01","protection_eligibility":"Ineligible","payer_id":"TJEWZZDMCEHPU","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"12:08:42 Jul 21, 2014 PDT","payment_status":"Refunded","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","mc_fee":"0.00","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","reason_code":"refund","custom":"","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","verify_sign":"A9SjQGkvKPz3A18BgbB.wurto1dNAZl3LjEg.Hdjtgza9oF9EZNiJk8N","payer_email":"vasja.forum@gmail.com","parent_txn_id":"00B09396A21740843","contact_phone":"017661995963","txn_id":"8MW58540H83728915","payment_type":"instant","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"275a55097271"}'),
(24, '{"mc_gross":"30.00","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"13:36:00 Jul 22, 2014 PDT","payment_status":"Pending","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"AF6v9UX3.7dFikGoYcexgXRvurU2ABlKeWg55REZHsjGzX.GoINp8Jd2","payer_email":"vasja.forum@gmail.com","contact_phone":"017661995963","txn_id":"0RC557283E7011703","payment_type":"echeck","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","pending_reason":"echeck","txn_type":"web_accept","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"463115ec167a6"}'),
(25, '{"mc_gross":"30.00","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"13:36:00 Jul 22, 2014 PDT","payment_status":"Denied","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"Ax-xV94Gjh9eM3Of7XyHsgJJkyA5AWhAUGnzVDozvBaMa6q0.WmyNYwq","payer_email":"vasja.forum@gmail.com","contact_phone":"017661995963","txn_id":"0RC557283E7011703","payment_type":"echeck","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"c9a90c7e29b64"}'),
(26, '{"mc_gross":"30.00","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"13:56:50 Jul 22, 2014 PDT","payment_status":"Pending","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"AqoI8eHDorZyktwxhnIbuS1baDawAkE0ma0Psbm0357nUD-oZnRrzvbO","payer_email":"vasja.forum@gmail.com","contact_phone":"017661995963","txn_id":"1PG72829GD797960H","payment_type":"echeck","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","pending_reason":"echeck","txn_type":"web_accept","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"51d4d981324f"}'),
(27, '{"mc_gross":"30.00","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"13:56:50 Jul 22, 2014 PDT","payment_status":"Denied","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"AKBwteUcdUfxKNWtREqRnwPpHzFEALnLoyPwR40lRjuZeYN3H-Kj3iRM","payer_email":"vasja.forum@gmail.com","contact_phone":"017661995963","txn_id":"1PG72829GD797960H","payment_type":"echeck","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"7bffd0b315901"}'),
(28, '[]'),
(29, '{"mc_gross":"30.00","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"14:09:01 Jul 22, 2014 PDT","payment_status":"Pending","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"At10rxPQp58ZTBUh19ab7zC4kum9Ao3ImQFy3jOcNSejG8QBHMHf2Vjb","payer_email":"vasja.forum@gmail.com","contact_phone":"","txn_id":"2XS771179A239200M","payment_type":"echeck","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","pending_reason":"echeck","txn_type":"web_accept","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"8184a7cbca4e6"}'),
(30, '{"mc_gross":"30.00","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"14:09:01 Jul 22, 2014 PDT","payment_status":"Denied","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"AnJ2HUJsm40z244.ABNEwFR12hcFAXcjzpTzqPrhXWB836KMqmpTtphl","payer_email":"vasja.forum@gmail.com","contact_phone":"","txn_id":"2XS771179A239200M","payment_type":"echeck","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"4fb0fcda7ed57"}'),
(31, '{"mc_gross":"0.01","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"14:16:14 Jul 22, 2014 PDT","payment_status":"Completed","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","mc_fee":"0.01","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"ApZ5RtMCECL8QWoQsbD-F6CJR7mEAEW2kMataXCswUFCVmFIAKuLxGwh","payer_email":"vasja.forum@gmail.com","contact_phone":"017661995963","txn_id":"7S95291635898104X","payment_type":"instant","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"285c8fe0a6a16"}'),
(32, '{"mc_gross":"-0.01","protection_eligibility":"Ineligible","payer_id":"TJEWZZDMCEHPU","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"14:17:59 Jul 22, 2014 PDT","payment_status":"Refunded","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","mc_fee":"-0.01","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","reason_code":"refund","custom":"","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","verify_sign":"AZQoAhq.vddbP-Ef8J.CK5niy7g1AeCBGiHsG2g7DZCeSwbGRijSwv-u","payer_email":"vasja.forum@gmail.com","parent_txn_id":"7S95291635898104X","contact_phone":"017661995963","txn_id":"8A688431V0559303E","payment_type":"instant","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"79f210608d81f"}'),
(33, '{"mc_gross":"0.01","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"13:34:20 Sep 01, 2014 PDT","payment_status":"Completed","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","mc_fee":"0.01","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"AHkrwUHq-Ag5AQSSiZL7rTWCohV0Ap2bxaWkJd-UvI3Yfr6jCVWya7lE","payer_email":"vasja.forum@gmail.com","contact_phone":"017661995963","txn_id":"84B466402X3714500","payment_type":"instant","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"428523da1e85d"}'),
(34, '{"mc_gross":"0.01","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"TJEWZZDMCEHPU","tax":"0.00","address_street":"Weissenseer Weg 13\\r\\nbei Kharitonova","payment_date":"13:44:32 Sep 12, 2014 PDT","payment_status":"Completed","charset":"UTF-8","address_zip":"10367","first_name":"Sergejs","mc_fee":"0.01","address_country_code":"DE","address_name":"Sergejs Lavrovs","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Germany","address_city":"Berlin","quantity":"1","verify_sign":"AacFY6Cpltu52uCYI1Se08WR2wAeANFJcbfo7ruEYALMCQFhXm8Gi7s9","payer_email":"vasja.forum@gmail.com","contact_phone":"017661995963","txn_id":"7T5643707E521020B","payment_type":"instant","btn_id":"83676686","last_name":"Lavrovs","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"DE","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"123cd8c6752b9"}'),
(35, '{"mc_gross":"3.50","protection_eligibility":"Ineligible","address_status":"unconfirmed","payer_id":"GC9DK5TGPKATC","tax":"0.00","address_street":"Satiksmes 43-71","payment_date":"11:22:51 Mar 23, 2015 PDT","payment_status":"Completed","charset":"UTF-8","address_zip":"LV-3007","first_name":"Vitalijs","mc_fee":"0.47","address_country_code":"LV","address_name":"Vitalijs Virkunens","notify_version":"3.8","custom":"","payer_status":"verified","business":"valerij.lavrov@inbox.lv","address_country":"Latvia","address_city":"Jelgava","quantity":"1","verify_sign":"A0qx6N2ej3Fhd09oDFnYZSe0gBK7ABUOBjdXXxXHWzV6VlAxn3tMdEnq","payer_email":"vitaly.virkunen@gmail.com","contact_phone":"+371 37129552263","txn_id":"4L45488311800562X","payment_type":"instant","btn_id":"83676686","last_name":"Virkunens","address_state":"","receiver_email":"valerij.lavrov@inbox.lv","payment_fee":"","shipping_discount":"0.00","insurance_amount":"0.00","receiver_id":"TYE3W3BGCLBCA","txn_type":"web_accept","item_name":"WorkSafe Precision 12 Paar Gr. 09","discount":"0.00","mc_currency":"EUR","item_number":"002","residence_country":"LV","shipping_method":"Default","handling_amount":"0.00","transaction_subject":"","payment_gross":"","shipping":"0.00","ipn_track_id":"62190af94acfa"}');

-- --------------------------------------------------------

--
-- Структура таблицы `payments`
--

CREATE TABLE IF NOT EXISTS `payments` (
  `id` int(6) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `address` varchar(150) NOT NULL,
  `zip` int(10) NOT NULL,
  `email` varchar(30) NOT NULL,
  `phone` varchar(30) NOT NULL,
  `item_name` varchar(50) NOT NULL,
  `trid` varchar(30) NOT NULL,
  `status` varchar(20) NOT NULL,
  `archive` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=15 ;

--
-- Дамп данных таблицы `payments`
--

INSERT INTO `payments` (`id`, `name`, `address`, `zip`, `email`, `phone`, `item_name`, `trid`, `status`, `archive`) VALUES
(12, 'Sergejs Lavrovs', 'Weissenseer Weg 13\r\nbei Kharitonova', 10367, 'vasja.forum@gmail.com', '017661995963', 'WorkSafe Precision 12 Paar Gr. 09', '84B466402X3714500', 'Completed', 1),
(13, 'Sergejs Lavrovs', 'Weissenseer Weg 13\r\nbei Kharitonova', 10367, 'vasja.forum@gmail.com', '017661995963', 'WorkSafe Precision 12 Paar Gr. 09', '7T5643707E521020B', 'Completed', 1),
(14, 'Vitalijs Virkunens', 'Satiksmes 43-71', 0, 'vitaly.virkunen@gmail.com', '+371 37129552263', 'WorkSafe Precision 12 Paar Gr. 09', '4L45488311800562X', 'Completed', 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
